In [1]:
import pandas as pd

In [15]:
portfolio = pd.read_csv('portfolio_main.csv')\
        # .rename(columns={'Unnamed: 0': 'Название'})\
        # .dropna(axis=0)\
        # .set_index('Название')

In [16]:
portfolio

,Котировки,НКД,Количество,Средняя цена,Комиссия,Текущая цена,"P/L, руб.","P/L, %"
SBMX,19.5700,NaN,1030,16.4160,4.98,20157.10,3248.62,19.21
SBER,299.5100,NaN,100,258.5800,20.75,29951.00,4093.00,15.83
MTSS,299.8000,NaN,60,279.3200,13.47,17988.00,1228.80,7.33
GAZP,157.7400,NaN,90,167.5900,13.57,14196.60,-886.50,-5.88
LKOH,7646.5000,NaN,3,6425.0000,13.00,22939.50,3664.50,19.01
MGNT,7833.0000,NaN,3,5769.7600,13.28,23499.00,6189.72,35.76
YNDX,3950.0000,NaN,2,2458.8700,3.74,7900.00,2982.26,60.64
CHMF,1859.2000,NaN,6,1405.0700,6.22,11155.20,2724.78,32.32
AFKS,23.9290,NaN,500,17.3780,7.35,11964.50,3275.50,37.70
IRAO,4.2535,NaN,2300,4.1027,7.29,9783.05,346.84,3.68
MOEX,224.8200,NaN,50,213.4800,7.55,11241.00,567.00,5.31
SBGD,20.4450,NaN,184,19.5800,0.90,3761.88,159.16,4.42

In [17]:
benchmark = {
    'SBMX': 10,
    'RU000A101FA1': 20,
    'SBER': 15,
    'MTSS': 10,
    'GAZP': 8,
    'LKOH': 10,
    'MGNT': 9,
    'YNDX': 3,
    'CHMF': 5,
    'AFKS': 5,
    'IRAO': 5
}

In [19]:
# portfolio.loc['RU000A101FA1', 'Котировки'] = portfolio.loc['RU000A101FA1', 'Котировки'] / 100 * 1000
portfolio['Текущая цена'] = portfolio['Котировки'] * portfolio['Количество']
portfolio['P/L'] = portfolio['Текущая цена'] - portfolio['Средняя цена'] * portfolio['Количество']
portfolio['P/L, %'] = (portfolio['Котировки'] * 100 / portfolio['Средняя цена'] - 100).round(2)
current_price_sum = (portfolio['Текущая цена'].sum()).round(2)
average_price_sum = ((portfolio['Средняя цена'] * portfolio['Количество']).sum()).round(2)
PL_sum = (portfolio['P/L'].sum()).round(2)
PL_per_sum = current_price_sum * 100 / average_price_sum - 100
portfolio['Пропорции, %'] = (portfolio['Текущая цена'] / current_price_sum * 100).round(2)
proportions_sum = (portfolio['Пропорции, %'].sum()).round(2)
portfolio['Бенчмарк, %'] = benchmark

In [20]:
portfolio

,Котировки,НКД,Количество,Средняя цена,Комиссия,Текущая цена,"P/L, руб.","P/L, %",P/L,"Пропорции, %","Бенчмарк, %"
SBMX,19.5700,NaN,1030,16.4160,4.98,20157.10,3248.62,19.21,3248.62,10.92,10.0
SBER,299.5100,NaN,100,258.5800,20.75,29951.00,4093.00,15.83,4093.00,16.23,15.0
MTSS,299.8000,NaN,60,279.3200,13.47,17988.00,1228.80,7.33,1228.80,9.75,10.0
GAZP,157.7400,NaN,90,167.5900,13.57,14196.60,-886.50,-5.88,-886.50,7.69,8.0
LKOH,7646.5000,NaN,3,6425.0000,13.00,22939.50,3664.50,19.01,3664.50,12.43,10.0
MGNT,7833.0000,NaN,3,5769.7600,13.28,23499.00,6189.72,35.76,6189.72,12.73,9.0
YNDX,3950.0000,NaN,2,2458.8700,3.74,7900.00,2982.26,60.64,2982.26,4.28,3.0
CHMF,1859.2000,NaN,6,1405.0700,6.22,11155.20,2724.78,32.32,2724.78,6.04,5.0
AFKS,23.9290,NaN,500,17.3780,7.35,11964.50,3275.50,37.70,3275.50,6.48,5.0
IRAO,4.2535,NaN,2300,4.1027,7.29,9783.05,346.84,3.68,346.84,5.30,5.0
MOEX,224.8200,NaN,50,213.4800,7.55,11241.00,567.00,5.31,567.00,6.09,NaN
SBGD,20.4450,NaN,184,19.5800,0.90,3761.88,159.16,4.42,159.16,2.04,NaN

In [35]:
# portfolio.loc['Итог'] = [None, None, average_price_sum, current_price_sum, PL_sum, PL_per_sum, proportions_sum]

In [36]:
portfolio['Разница, %'] = (portfolio['Пропорции, %'] * 100 / portfolio['Бенчмарк, %'] - 100).round(2)

In [37]:
portfolio

,Котировки,Количество,Средняя цена,Текущая цена,P/L,"P/L, %","Пропорции, %","Бенчмарк, %","Разница, %"
Название,,,,,,,,,
SBMX,17.1500,830,15.7570,14234.5,1156.19,8.84,16.12,10,61.20
RU000A101FA1,996.3400,35,987.4200,34871.9,312.20,0.90,39.50,20,97.50
SBER,249.2500,40,224.6600,9970.0,983.60,10.95,11.29,15,-24.73
MTSS,287.5500,20,300.9000,5751.0,-267.00,-4.44,6.51,10,-34.90
GAZP,171.4400,30,174.1700,5143.2,-81.90,-1.57,5.83,8,-27.12
LKOH,5896.0000,1,4821.3300,5896.0,1074.67,22.29,6.68,10,-33.20
MGNT,5803.0000,1,4186.2600,5803.0,1616.74,38.62,6.57,9,-27.00
YNDX,2636.0000,1,2642.3800,2636.0,-6.38,-0.24,2.99,3,-0.33
CHMF,1334.8000,1,1276.7500,1334.8,58.05,4.55,1.51,5,-69.80
AFKS,18.2300,100,17.7600,1823.0,47.00,2.65,2.06,5,-58.80
IRAO,4.1265,200,4.1628,825.3,-7.26,-0.87,0.93,5,-81.40

In [38]:
portfolio['Бенчмарк, %'].sum()

100